## $Id$

#load 'tasks/setup.rb'

##SITE.output_dir = ""
#task :default => :build

#desc 'deploy the site to the webserver'
#task :deploy => [:build, 'deploy:rsync']

## EOF
#


desc 'Upload files to rubyforge server'
task 'upload' do
  Dir.chdir('output') do
    cmd = "scp -r * #{ENV['RUBYFORGE_NAME']}@rubyforge.org:/var/www/gforge-projects/monkeybars"
    sh cmd
  end
end

