## $Id$

#load 'tasks/setup.rb'

##SITE.output_dir = ""
#task :default => :build

#desc 'deploy the site to the webserver'
#task :deploy => [:build, 'deploy:rsync']

## EOF
#


desc 'Upload files to neurogami server.'
task 'upload' do
    cmd = "scp -v -P #{ENV['MONKEYBARS_SERVER_PORT']} -r public #{ENV['MONKEYBARS_SERVER_ID']}:/usr/local/webdev/monkeybars.org/"
    warn cmd
    sh cmd
end

