require 'rake'
require 'fileutils'

rule(/generate.+/) do |t|
  match = /generate (.+)/.match(t.to_s)
  if match[1]
    generate_tuple(match[1])
  end
end

def generate_tuple(path)
  FileUtils.mkdir_p path.gsub("\\", "/")
  FileUtils.cd(path)
  name = path.split("/").last
  controller = File.new("#{name}_controller.rb", "w+")
  File.new("#{name}_model.rb")
  view = File.new("#{name}_view.rb", "w+")
  
  name = camelize(name)
  controller << <<-ENDL
    class #{name}Controller < Monkeybars::Controller
      set_model '#{name}Model'
      set_view '#{name}View'
    end
  ENDL
  
  view << <<-ENDL
    class #{name}View < Monkeybars::View
      set_java_class ''
    end
  ENDL
end

def camelize(first_letter_in_uppercase = true)
  if first_letter_in_uppercase
    self.to_s.gsub(/\/(.?)/) { "::" + $1.upcase }.gsub(/(^|_)(.)/) { $2.upcase }
  else
    self.to_s[0..0] + camelize(self.to_s)[1..-1]
  end
end

# End of generator tasks =======================================================

