require 'rake'
require 'spec/rake/spectask'

Dir.glob("tasks/**/*.rake").each do |rake_file|
  load File.expand_path(File.dirname(__FILE__) + "/" + rake_file)
end

desc "Run all specs"
Spec::Rake::SpecTask.new do |t|
  t.libs << File.expand_path(File.dirname(__FILE__) + "/lib")
  t.libs << File.expand_path(File.dirname(__FILE__) + "/src")
  t.spec_files = FileList['test/unit/**/*_spec.rb']
  t.spec_opts = ['--color']
end