/*
 * ListFrame.java
 *
 * Created on June 15, 2008, 10:50 PM
 */

package list;

/**
 *
 * @author  logan
 */
public class ListFrame extends javax.swing.JFrame {

    /** Creates new form ListFrame */
    public ListFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        items_list = new javax.swing.JList();
        search_landing_panel = new javax.swing.JPanel();
        searchPanel1 = new search.SearchPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Worst Movies Ever");

        items_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Manos: The Hands of Fate", "Plan 9 from Outer Space", "Anus Magillicutty", "Monster A Go Go", "Ballistic: Ecks vs. Sever", "Santa Claus Conquers the Martians", "From Justin to Kelly", "An Alan Smithee Film: Burn Hollywood Burn", "Batman & Robin" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(items_list);

        search_landing_panel.setLayout(new javax.swing.BoxLayout(search_landing_panel, javax.swing.BoxLayout.LINE_AXIS));
        search_landing_panel.add(searchPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .add(search_landing_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(search_landing_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList items_list;
    private javax.swing.JScrollPane jScrollPane1;
    private search.SearchPanel searchPanel1;
    private javax.swing.JPanel search_landing_panel;
    // End of variables declaration//GEN-END:variables

}
