/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseFilePanel.java
 *
 * Created on 2009-3-7, 11:11:20
 */

package filechooser;

/**
 *
 * @author daiwhea
 */
public class ChooseFilePanel extends javax.swing.JPanel {

    /** Creates new form ChooseFilePanel */
    public ChooseFilePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filename_text_field = new javax.swing.JTextField();
        choose_file_button = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(210, 25));

        filename_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filename_text_fieldActionPerformed(evt);
            }
        });

        choose_file_button.setText("Choose");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(filename_text_field, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(choose_file_button))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(choose_file_button)
                    .add(filename_text_field, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {choose_file_button, filename_text_field}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    private void filename_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filename_text_fieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_filename_text_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choose_file_button;
    private javax.swing.JTextField filename_text_field;
    // End of variables declaration//GEN-END:variables

}
