/*
 * Hello.java
 *
 * Created on March 29, 2008, 7:41 PM
 */



/**
 *
 * @author  david
 */
public class Hello extends javax.swing.JFrame {
    
    /** Creates new form Hello */
    public Hello() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        improve_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(273, 96));

        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Message goes here");
        message.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        message.setPreferredSize(new java.awt.Dimension(300, 36));
        jPanel1.add(message);

        improve_button.setText("Improve");
        jPanel1.add(improve_button);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hello().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton improve_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
    
}
