/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiffFrame.java
 *
 * Created on 2009-3-7, 10:53:00
 */

package diff;

/**
 *
 * @author daiwhea
 */
public class DiffFrame extends javax.swing.JFrame {

    /** Creates new form DiffFrame */
    public DiffFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        filechooser_panel1 = new javax.swing.JPanel();
        exchange_button = new javax.swing.JButton();
        filechooser_panel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        split_panel = new javax.swing.JSplitPane();
        diff_panel_placeholder_a = new javax.swing.JPanel();
        diff_panel_placeholder_b = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_item_new_window = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_item_clear_both = new javax.swing.JMenuItem();
        menu_item_exit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_item_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jruby Diff");
        setName("main_frame"); // NOI18N

        filechooser_panel1.setBackground(new java.awt.Color(255, 204, 204));
        filechooser_panel1.setLayout(new java.awt.GridLayout(1, 0));

        exchange_button.setText("<=>");
        exchange_button.setToolTipText("Exchange the selected files to compare.");
        exchange_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchange_buttonActionPerformed(evt);
            }
        });

        filechooser_panel2.setBackground(new java.awt.Color(255, 204, 204));
        filechooser_panel2.setLayout(new java.awt.GridLayout(1, 0));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(filechooser_panel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .add(52, 52, 52)
                .add(exchange_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(51, 51, 51)
                .add(filechooser_panel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                .add(filechooser_panel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .add(filechooser_panel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .add(exchange_button, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {exchange_button, filechooser_panel1, filechooser_panel2}, org.jdesktop.layout.GroupLayout.VERTICAL);

        split_panel.setDividerLocation(350);

        diff_panel_placeholder_a.setLayout(new java.awt.GridLayout(1, 0));
        split_panel.setLeftComponent(diff_panel_placeholder_a);

        diff_panel_placeholder_b.setLayout(new java.awt.GridLayout(1, 0));
        split_panel.setRightComponent(diff_panel_placeholder_b);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(split_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(split_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        menu_item_new_window.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_item_new_window.setText("New Window");
        menu_item_new_window.setToolTipText("Open a new JRuby Diff Window");
        jMenu1.add(menu_item_new_window);

        jMenu4.setText("Clear");

        menu_item_clear_both.setText("Both");
        jMenu4.add(menu_item_clear_both);

        jMenu1.add(jMenu4);

        menu_item_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menu_item_exit.setText("Quit");
        jMenu1.add(menu_item_exit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");

        menu_item_about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menu_item_about.setMnemonic('C');
        menu_item_about.setText("Content");
        jMenu3.add(menu_item_about);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(496, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .add(41, 41, 41)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exchange_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchange_buttonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_exchange_buttonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiffFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel diff_panel_placeholder_a;
    private javax.swing.JPanel diff_panel_placeholder_b;
    private javax.swing.JButton exchange_button;
    private javax.swing.JPanel filechooser_panel1;
    private javax.swing.JPanel filechooser_panel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menu_item_about;
    private javax.swing.JMenuItem menu_item_clear_both;
    private javax.swing.JMenuItem menu_item_exit;
    private javax.swing.JMenuItem menu_item_new_window;
    private javax.swing.JSplitPane split_panel;
    // End of variables declaration//GEN-END:variables

}
