/*
 * Any changes made to this file will not show up when running specs until you
 * run the test_prepare Rake task.  That task recreates the jar that this file
 * lives in and makes it available to the spec.
 *
 */

package org.monkeybars;

public class TestView extends javax.swing.JFrame {
    
    private int primitiveVariable = 20;
    private Integer objectVariable = new Integer(30);
    
    /** Creates new form TestView */
    public TestView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testLabel = new javax.swing.JLabel();
        testButton = new javax.swing.JButton();
        testTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        testLabel.setText("A Test Label");
        testLabel.setName("testLabel"); // NOI18N
        getContentPane().add(testLabel);
        testLabel.setBounds(20, 20, 77, 16);

        testButton.setText("Press me");
        getContentPane().add(testButton);
        testButton.setBounds(140, 250, 120, 29);

        testTextField.setText("A text field");
        getContentPane().add(testTextField);
        testTextField.setBounds(300, 20, 84, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton testButton;
    private javax.swing.JLabel testLabel;
    private javax.swing.JTextField testTextField;
    // End of variables declaration//GEN-END:variables
    
}
