/*
 * PaymentFrame.java
 *
 * Created on June 7, 2008, 9:58 PM
 */

package payment;

/**
 *
 * @author  logan
 */
public class PaymentFrame extends javax.swing.JFrame {

    /** Creates new form PaymentFrame */
    public PaymentFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billing_address_title_panel = new javax.swing.JPanel();
        addressPanel1 = new address.AddressPanel();
        shipping_address_title_panel = new javax.swing.JPanel();
        addressPanel2 = new address.AddressPanel();
        same_addess_check_box = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment Information");

        billing_address_title_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Billing Address"));
        billing_address_title_panel.setLayout(new javax.swing.BoxLayout(billing_address_title_panel, javax.swing.BoxLayout.LINE_AXIS));
        billing_address_title_panel.add(addressPanel1);

        shipping_address_title_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Shipping Address"));
        shipping_address_title_panel.setLayout(new javax.swing.BoxLayout(shipping_address_title_panel, javax.swing.BoxLayout.LINE_AXIS));
        shipping_address_title_panel.add(addressPanel2);

        same_addess_check_box.setSelected(true);
        same_addess_check_box.setText("Shipping address same as billing");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(billing_address_title_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(same_addess_check_box)
                    .add(shipping_address_title_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(billing_address_title_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(same_addess_check_box)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(shipping_address_title_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private address.AddressPanel addressPanel1;
    private address.AddressPanel addressPanel2;
    private javax.swing.JPanel billing_address_title_panel;
    private javax.swing.JCheckBox same_addess_check_box;
    private javax.swing.JPanel shipping_address_title_panel;
    // End of variables declaration//GEN-END:variables

}
