/*
 * User.java
 *
 * Created on June 11, 2008, 3:03 PM
 */

package user;

/**
 *
 * @author  logan
 */
public class UserPanel extends javax.swing.JPanel {

    /** Creates new form User */
    public UserPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        first_name_text_field = new javax.swing.JTextField();
        last_name_text_field = new javax.swing.JTextField();
        age_text_field = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout());

        first_name_text_field.setEditable(false);
        first_name_text_field.setText("First Name");
        add(first_name_text_field);

        last_name_text_field.setEditable(false);
        last_name_text_field.setText("Last Name");
        add(last_name_text_field);

        age_text_field.setEditable(false);
        age_text_field.setText("03/03/2008");
        add(age_text_field);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_text_field;
    private javax.swing.JTextField first_name_text_field;
    private javax.swing.JTextField last_name_text_field;
    // End of variables declaration//GEN-END:variables

}
